# -*- coding: utf-8 -*-
#
# Copyright (C) 2020-2024 CERN.
# Copyright (C) 2020 Northwestern University.
# Copyright (C) 2022 Graz University of Technology.
# Copyright (C) 2023 Rambaud Pierrick.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

name: CI

on:
  push:
    branches:
      - master
      - "feature/*"
      - "maint-**"
  pull_request:
    branches:
      - master
      - "maint-**"
      - "feature/**"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 3 * * 6"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason"
        required: false
        default: "Manual trigger"

jobs:
  Python:
      uses: inveniosoftware/workflows/.github/workflows/tests-python.yml@master
